package com.fashion.mjysite.entity;

import java.io.Serializable;

public class Atta implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_atta.id
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_atta.forcode
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    private String formcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_atta.attaname
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    private String attaname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_atta.attalocal
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    private String attaurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_atta.flag
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    private String flag;

    private int attano;

    public int getAttano() {
        return attano;
    }

    public void setAttano(int attano) {
        this.attano = attano;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_atta.id
     *
     * @return the value of sys_atta.id
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_atta.id
     *
     * @param id the value for sys_atta.id
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_atta.forcode
     *
     * @return the value of sys_atta.forcode
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public String getFormcode() {
        return formcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_atta.forcode
     *
     * @param formcode the value for sys_atta.forcode
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public void setFormcode(String formcode) {
        this.formcode = formcode == null ? null : formcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_atta.attaname
     *
     * @return the value of sys_atta.attaname
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public String getAttaname() {
        return attaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_atta.attaname
     *
     * @param attaname the value for sys_atta.attaname
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public void setAttaname(String attaname) {
        this.attaname = attaname == null ? null : attaname.trim();
    }


    public String getAttaurl() {
        return attaurl;
    }

    public void setAttaurl(String attaurl) {
        this.attaurl = attaurl == null ? null : attaurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_atta.flag
     *
     * @return the value of sys_atta.flag
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_atta.flag
     *
     * @param flag the value for sys_atta.flag
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }
}