package com.fashion.mjysite.entity;

import org.springframework.format.annotation.DateTimeFormat;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class Form {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_form.id
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_form.formcdoe
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    private String formcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_form.formtype
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    private String formtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_form.dept
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    private String dept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_form.supplier
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    private String supplier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_form.delivery
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    private String delivery;
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_form.originator
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    private String originator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_form.totalprice
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    private BigDecimal totalprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_form.signflag
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    private String signflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_form.flag
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    private String flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_form.creatdate
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    private Date creatdate;
    private List<FormDetail> formDetailList;

    public List<FormDetail> getFormDetailList() {
        return formDetailList;
    }

    public void setFormDetailList(List<FormDetail> formDetailList) {
        this.formDetailList = formDetailList;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_form.applydate
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     接收参数为实体类包含时间格式需要指定时间格式,不然会报400错误*/

    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date applydate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_form.id
     *
     * @return the value of cost_form.id
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_form.id
     *
     * @param id the value for cost_form.id
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_form.formcdoe
     *
     * @return the value of cost_form.formcdoe
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    public String getFormcode() {
        return formcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_form.formcdoe
     *
     * @param formcode the value for cost_form.formcdoe
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    public void setFormcode(String formcode) {
        this.formcode = formcode == null ? null : formcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_form.formtype
     *
     * @return the value of cost_form.formtype
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    public String getFormtype() {
        return formtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_form.formtype
     *
     * @param formtype the value for cost_form.formtype
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    public void setFormtype(String formtype) {
        this.formtype = formtype == null ? null : formtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_form.dept
     *
     * @return the value of cost_form.dept
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_form.dept
     *
     * @param dept the value for cost_form.dept
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    public void setDept(String dept) {
        this.dept = dept == null ? null : dept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_form.supplier
     *
     * @return the value of cost_form.supplier
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    public String getSupplier() {
        return supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_form.supplier
     *
     * @param supplier the value for cost_form.supplier
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    public void setSupplier(String supplier) {
        this.supplier = supplier == null ? null : supplier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_form.delivery
     *
     * @return the value of cost_form.delivery
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    public String getDelivery() {
        return delivery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_form.delivery
     *
     * @param delivery the value for cost_form.delivery
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    public void setDelivery(String delivery) {
        this.delivery = delivery == null ? null : delivery.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_form.originator
     *
     * @return the value of cost_form.originator
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    public String getOriginator() {
        return originator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_form.originator
     *
     * @param originator the value for cost_form.originator
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    public void setOriginator(String originator) {
        this.originator = originator == null ? null : originator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_form.totalprice
     *
     * @return the value of cost_form.totalprice
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    public BigDecimal getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_form.totalprice
     *
     * @param totalprice the value for cost_form.totalprice
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    public void setTotalprice(BigDecimal totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_form.signflag
     *
     * @return the value of cost_form.signflag
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    public String getSignflag() {
        return signflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_form.signflag
     *
     * @param signflag the value for cost_form.signflag
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    public void setSignflag(String signflag) {
        this.signflag = signflag == null ? null : signflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_form.flag
     *
     * @return the value of cost_form.flag
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_form.flag
     *
     * @param flag the value for cost_form.flag
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_form.creatdate
     *
     * @return the value of cost_form.creatdate
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    public Date getCreatdate() {
        return creatdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_form.creatdate
     *
     * @param creatdate the value for cost_form.creatdate
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    public void setCreatdate(Date creatdate) {
        this.creatdate = creatdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_form.applydate
     *
     * @return the value of cost_form.applydate
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    public Date getApplydate() {
        return applydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_form.applydate
     *
     * @param applydate the value for cost_form.applydate
     *
     * @mbg.generated Thu Aug 01 11:45:24 CST 2019
     */
    public void setApplydate(Date applydate) {
        this.applydate = applydate;
    }
}